<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >
 
    <material name="red_laser">
        <color rgba="1 0 0 1" />
    </material>   

    <material name="black_lidar">
        <color rgba="0 0 0 1" />
    </material>

    <xacro:macro name="inertial_cylinder" params="mass radius length">
        <inertial>
            <mass value="${mass}"/>
            <origin xyz="0 0 ${length / 2}" rpy="0 0 0"/>
            <inertia ixx="${1/2 * mass * radius * radius}" iyy="${1/2 * mass * radius * radius}" izz="${1/12 * mass * (3 * radius * radius + length * length)}"/>
        </inertial>
    </xacro:macro>
    
    <joint name="laser_joint" type="fixed">
        <parent link="chassis"/>
        <child link="laser_frame"/>
        <origin xyz="0.14 0 0.175" rpy="0 0 ${pi}"/>
    </joint>
 
    <link name="laser_frame">
        <visual>
            <origin xyz="0 0 -0.01" rpy="0 0 0"/>
            <geometry>
                <mesh filename="package://cengaver_rover_description/meshes/rplidar_a1.STL" />
            </geometry>
            <material name="black_lidar"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <mesh filename="package://cengaver_rover_description/meshes/rplidar_a1.STL" />
            </geometry>
        </collision>
    </link>
 
 
    <gazebo reference="laser_frame">
        <material>Gazebo/Black</material>
 
        <sensor name="laser" type="ray">
            <pose> 0 0 0 0 0 0 </pose>
            <visualize>true</visualize>
            <update_rate>5.5</update_rate>
            <ray>
                <scan>
                    <horizontal>
                        <samples>363</samples>
                        <min_angle>-3.14</min_angle>
                        <max_angle>3.14</max_angle>
                    </horizontal>
                </scan>
                <range>
                    <min>0.15</min>
                    <max>6</max>
                </range>
            </ray>
            <plugin name="laser_controller" filename="libgazebo_ros_ray_sensor.so">
                <ros>
                    <argument>~/out:=scan</argument>
                </ros>
                <output_type>sensor_msgs/LaserScan</output_type>
                <frame_name>laser_frame</frame_name>
            </plugin>
        </sensor>
    </gazebo>
 
</robot>
